### ISSUE TITLE
symbols = DataSymbols(["IBM", "MSFT"])

### ISSUE THREAD

**Issue by femtotrader** [femtotrader/DataReaders.jl#22]
symbols = DataSymbols(["IBM", "MSFT"])

should be replaced by

    symbols = DataSymbol.(["IBM", "MSFT"])

**Comment by iblis17** [comment]
FYR
There is a fabulous macro in 0.6: `@.`

```julia
symbols = @. DataSymbol(["IBM", "MSFT"])
```

**Comment by femtotrader** [comment]
I decided to use

```julia
symbols = DataSymbol.(["IBM", "MSFT"])
```

because I think we should avoid macro when it's possible and efficient
